# Generated by Django 5.1.1 on 2024-10-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Категория для новостей')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
