# Generated by Django 5.1.1 on 2024-10-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_categorynews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorynews',
            options={'verbose_name': '', 'verbose_name_plural': 'Категории для новостей'},
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.categorynews'),
        ),
    ]
