# Generated by Django 5.1.1 on 2024-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_news', to='news.categorynews'),
        ),
    ]
