# Generated by Django 5.1.1 on 2024-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(default='по-умолчанию', verbose_name='Описание'),
        ),
    ]
