# Generated by Django 4.2.7 on 2024-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                (
                    "image1",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 1"),
                ),
                (
                    "image2",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 2"),
                ),
                (
                    "image3",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 3"),
                ),
                ("facebook", models.URLField()),
                ("twitter", models.URLField()),
                ("youtube", models.URLField()),
                ("linkedin", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Настройка Главной",
            },
        ),
    ]
