# Generated by Django 4.2.7 on 2024-09-20 14:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_shape"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 1"),
                ),
                (
                    "image2",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 2"),
                ),
                (
                    "image3",
                    models.ImageField(upload_to="settings/", verbose_name="Фото 3"),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name_plural": " О нас",
            },
        ),
    ]
