# Generated by Django 5.1 on 2024-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo_image/')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('water_mark', models.CharField(max_length=155, verbose_name='Водяной знак на баннере')),
                ('banner', models.ImageField(upload_to='banner_image/')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Основные настройки сайта',
            },
        ),
    ]
